// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckClaudeInstalled() {
  return window['go']['main']['App']['CheckClaudeInstalled']();
}

export function DeleteThreads(arg1) {
  return window['go']['main']['App']['DeleteThreads'](arg1);
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetThreadLogs(arg1) {
  return window['go']['main']['App']['GetThreadLogs'](arg1);
}

export function LoadSetting(arg1) {
  return window['go']['main']['App']['LoadSetting'](arg1);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function StartRun(arg1) {
  return window['go']['main']['App']['StartRun'](arg1);
}

export function StopRun(arg1) {
  return window['go']['main']['App']['StopRun'](arg1);
}

export function WriteAppLog(arg1) {
  return window['go']['main']['App']['WriteAppLog'](arg1);
}
