// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logstore} from '../models';
import {runner} from '../models';

export function CheckClaudeInstalled():Promise<string>;

export function DeleteThreads(arg1:string):Promise<void>;

export function GetLogPath():Promise<string>;

export function GetRecentLogs(arg1:number):Promise<Array<logstore.LogEntry>>;

export function GetThreadLogs(arg1:string):Promise<Array<logstore.LogEntry>>;

export function LoadSetting(arg1:string):Promise<string>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function SelectProjectDirectory():Promise<string>;

export function StartRun(arg1:runner.RunRequest):Promise<string>;

export function StopRun(arg1:string):Promise<void>;

export function WriteAppLog(arg1:string):Promise<void>;
